export const API_URL = {
  techniqueSearch: `${import.meta.env.VITE_BACKEND_BASE_URL}/techniqueSearch`,
  randomGame: `${import.meta.env.VITE_BACKEND_BASE_URL}/randomGame`,
  saveGame: `${import.meta.env.VITE_BACKEND_BASE_URL}/saveGame`,
  getTags: `${import.meta.env.VITE_BACKEND_BASE_URL}/tags`,
  getVoteTotals: `${import.meta.env.VITE_BACKEND_BASE_URL}/getVoteTotals`,
  trackVote: `${import.meta.env.VITE_BACKEND_BASE_URL}/trackVote`,
  getUserVotes: `${import.meta.env.VITE_BACKEND_BASE_URL}/getUserVotes`,
  addGame: `${import.meta.env.VITE_BACKEND_BASE_URL}/addGame`,
  addGameForVote: `${import.meta.env.VITE_BACKEND_BASE_URL}/addGameForVote`,
  getPieces: `${import.meta.env.VITE_BACKEND_BASE_URL}/getPieces`,
  gameTechniques: `${import.meta.env.VITE_BACKEND_BASE_URL}/gameTechniques`,
  getGamesForVote: `${import.meta.env.VITE_BACKEND_BASE_URL}/gamesForVote`,
  gamesForVote: `${import.meta.env.VITE_BACKEND_BASE_URL}/gamesForVote`,
  login: `${import.meta.env.VITE_BACKEND_BASE_URL}/login`,
  getOneUserGame: `${import.meta.env.VITE_BACKEND_BASE_URL}/getOneUserGame`,
  getSavedGames: `${import.meta.env.VITE_BACKEND_BASE_URL}/getSavedGames`,
  deleteSavedGame: `${import.meta.env.VITE_BACKEND_BASE_URL}/deleteSavedGame`,
  getUserCreatedGames: `${
    import.meta.env.VITE_BACKEND_BASE_URL
  }/getUserCreatedGames`,
  deleteCreated: `${import.meta.env.VITE_BACKEND_BASE_URL}/deleteCreated`,
  checkGoogleUser: `${import.meta.env.VITE_BACKEND_BASE_URL}/checkGoogleUser`,
  addGoogleUser: `${import.meta.env.VITE_BACKEND_BASE_URL}/addGoogleUser`,
  gameSearch: `${import.meta.env.VITE_BACKEND_BASE_URL}/gameSearch`,
};
