export const API_URL = {
  techniqueSearch: `${import.meta.env.BACKEND_BASE_URL}/techniqueSearch`,
  randomGame: `${import.meta.env.BACKEND_BASE_URL}/randomGame`,
  saveGame: `${import.meta.env.BACKEND_BASE_URL}/saveGame`,
  getTags: `${import.meta.env.BACKEND_BASE_URL}/tags`,
  getVoteTotals: `${import.meta.env.BACKEND_BASE_URL}/getVoteTotals`,
  trackVote: `${import.meta.env.BACKEND_BASE_URL}/trackVote`,
  getUserVotes: `${import.meta.env.BACKEND_BASE_URL}/getUserVotes`,
  addGame: `${import.meta.env.BACKEND_BASE_URL}/addGame`,
  addGameForVote: `${import.meta.env.BACKEND_BASE_URL}/addGameForVote`,
  getPieces: `${import.meta.env.BACKEND_BASE_URL}/getPieces`,
  getGameTechniques: `${import.meta.env.BACKEND_BASE_URL}/getGameTechniques`,
  getGamesForVote: `${import.meta.env.BACKEND_BASE_URL}/gamesForVote`,
  gamesForVote: `${import.meta.env.BACKEND_BASE_URL}/gamesForVote`,
};
