POST http://localhost:8080/addUser
Content-Type: application/json

{
    "firstName": "Miks",
    "lastName": "Silis",
    "country": "United Kingdom",
    "email": "mikssilis@gmail.com",
    "userName": "miks",
    "password": "pass"

}

###

GET http://localhost:8080/tags
Content-Content-Type: application/json

###
POST https://group-class-backend.onrender.com/getUserCreatedGames
Content-Type: application/json

{
    "userId": "6409d2992852aeb8e5b8ae3c"
}